import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import LoginButton from "../component/login-btn";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>pgvins</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world</h1>
      <LoginButton />
      <Link href="/auth/register">register</Link>
    </>
  );
};

export default Home;
